
---
- name: Install application on debian
  hosts: deb
  become: yes

  tasks:
  - name: Install apache
    apt: name=apache2 state=latest

  - name: start apache and enable it on the every boot
    service: name=apache2 state=started enabled=yes

- name: install application on centos
  hosts: cent
  become: yes

  tasks:
  - name: install httpd
    yum: name=httpd state=latest

  - name: start httpd
    service: name=httpd state=started enabled=yes
