---
- name: ansible check_errors
  hosts: all
  become: yes
  any_errors_fatal: true

  tasks:
    - name: task 1
      yum: name=treeeee state=latest
      ignore_errors: yes

    - name: task 2
      shell: echo Hello world
      register: results
#      failed_when: results.rc == 0
#      failed_when: "'world' in results.stdout"

    - debug:
        var: results

    - name: task 3
      shell: cat /home/2.txt
      register: results




    - name: task 4
      shell: echo Privet Mir




