---
- name: install Apache and upload my web page
  hosts: all
  become: yes

  vars:
    source_file: ./website/index.html
    destin_file: /var/www/html


  tasks:
  - name: check and print linux version
    debug: var=ansible_os_family


  - name: Install apache
    apt: name=apache2 state=latest

  - name: start apache and enable it on the every boot
    service: name=apache2 state=started enabled=yes

  - name: copy homepage to server
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: restart apache

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

